// Code generated by opc_codegen. DO NOT EDIT.
package opc_custom

import (
	"github.com/awcullen/opcua/ua"
	"reflect"
	"time"
)


type CutterLocationDataType struct {
	Position float64
	PositionEngineeringUnits ua.EUInformation
	CoordinateName string
}

type ProgramPositionDataType struct {
	ProgramName string
	BlockNumber uint32
	BlockContent string
	CallStackLevel uint32
}

type ToolData struct {
	Comment string
	DatabaseId string
	Name string
	ToolIndex int32
	ToolNumber int32
	Type string
	AttributeForPocket int32
	PlcStatus int32
	LastUsage time.Time
	LockedStatus int32
	AllowedOvertime int32
	CurrentLifetime int32
	MaximumLifetime int32
	MaximumLifetimeToolCall int32
	UsableLength int32
	MaximumSpeed float64
	LengthOffset int32
	RadiusOffset int32
	CarrierKinematics string
	ReplacementToolNumber int32
	LengthOversize int32
	Length int32
	NeckRadius float64
	Radius int32
	CuttingDirection int32
	LengthBreakageTolerance int32
	LengthTolerance int32
	RadiusBreakageTolerance int32
	RadiusTolerance int32
	CutterEdgeLength int32
	CuttingData string
	ToolEdgeMaterial string
	EdgeRadiusTolerance int32
	Liftoff int32
	ActiveFeedControlStrategy string
	AfcOverloadSwitchoff string
	AfcOverloadWarning string
	AfcReferencePower string
	PointAngle int32
	RadiusAtTip int32
	EdgeRadiusOversize int32
	CutterEdgeRadius int32
	NumberOfCutterEdges int32
	RadiusOversize int32
	MaximumPlungeAngle int32
	FrontfaceCutterWidth int32
	EdgeRadiusCompensationTable string
	ActiveChatterControl int32
}



func init() {
	namespace := "http://heidenhain.de/NC/"
	registerType(reflect.TypeOf(CutterLocationDataType{}), 5010, namespace)
	registerType(reflect.TypeOf(ProgramPositionDataType{}), 5013, namespace)
	registerType(reflect.TypeOf(ToolData{}), 5017, namespace)
}

