// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/polling/start": {
            "get": {
                "description": "Запускает опрос OPC UA для конкретного станка по UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polling"
                ],
                "summary": "Запустить мониторинг станка",
                "parameters": [
                    {
                        "description": "ID станка и интервал опроса (мс)",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connection.StartPollingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Мониторинг запущен",
                        "schema": {
                            "$ref": "#/definitions/swagger.PollingResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/swagger.IncorrectFormatError"
                        }
                    },
                    "404": {
                        "description": "Данные не найдены",
                        "schema": {
                            "$ref": "#/definitions/swagger.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/swagger.InternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/polling/stop": {
            "get": {
                "description": "Останавливает опрос OPC UA для конкретного станка по ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Polling"
                ],
                "summary": "Остановить мониторинг станка",
                "parameters": [
                    {
                        "description": "UUID станка",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connection.IDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Мониторинг запущен",
                        "schema": {
                            "$ref": "#/definitions/swagger.PollingResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/swagger.IncorrectFormatError"
                        }
                    },
                    "404": {
                        "description": "Данные не найдены",
                        "schema": {
                            "$ref": "#/definitions/swagger.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/swagger.InternalServerError"
                        }
                    }
                }
            }
        },
        "/connect": {
            "get": {
                "description": "Возвращает список активных соединений в пуле OPC UA",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Connection"
                ],
                "summary": "Получить пул соединений",
                "responses": {
                    "200": {
                        "description": "Список активных соединений",
                        "schema": {
                            "$ref": "#/definitions/swagger.GetConnectionPoolResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Подключение клиента для мониторинга станка: анонимно, по паролю или по сертификату. Передаётся JSON с данными для входа.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Connection"
                ],
                "summary": "Подключение клиента",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connection.ConnectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное подключение",
                        "schema": {
                            "$ref": "#/definitions/swagger.IDResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса или некорректные данные",
                        "schema": {
                            "$ref": "#/definitions/swagger.IncorrectFormatError"
                        }
                    },
                    "401": {
                        "description": "Некорректные данные",
                        "schema": {
                            "$ref": "#/definitions/swagger.IncorrectDataError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/swagger.InternalServerError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Закрывает соединение OPC UA по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Connection"
                ],
                "summary": "Отключение сессии",
                "parameters": [
                    {
                        "description": "ID для отключения",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connection.IDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное отключение",
                        "schema": {
                            "$ref": "#/definitions/swagger.DisconnectResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/swagger.IncorrectFormatError"
                        }
                    },
                    "404": {
                        "description": "Данные не найдены",
                        "schema": {
                            "$ref": "#/definitions/swagger.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/swagger.InternalServerError"
                        }
                    }
                }
            }
        },
        "/connect/check": {
            "post": {
                "description": "Проверяет состояние соединения OPC UA по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Connection"
                ],
                "summary": "Проверка соединения",
                "parameters": [
                    {
                        "description": "ID для проверки",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/connection.CheckConnectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о подключении",
                        "schema": {
                            "$ref": "#/definitions/swagger.CheckConnectionResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/swagger.IncorrectFormatError"
                        }
                    },
                    "404": {
                        "description": "Данные не найдены",
                        "schema": {
                            "$ref": "#/definitions/swagger.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/swagger.InternalServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "connection.CheckConnectionRequest": {
            "type": "object",
            "required": [
                "ID"
            ],
            "properties": {
                "ID": {
                    "type": "integer"
                }
            }
        },
        "connection.ConnectionInfoResponse": {
            "type": "object",
            "properties": {
                "UUID": {
                    "type": "string"
                },
                "config": {
                    "$ref": "#/definitions/models.ConnectionConfig"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2025-08-22T12:00:00Z"
                },
                "description": {
                    "type": "string"
                },
                "lastUsed": {
                    "type": "string",
                    "example": "2025-08-22T12:05:00Z"
                },
                "machineID": {
                    "type": "integer",
                    "example": 1
                },
                "sessionID": {
                    "type": "string",
                    "example": "ns=3;i=3093118269"
                },
                "status": {
                    "$ref": "#/definitions/connection.ConnectionStatusEnum"
                },
                "useCount": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "connection.ConnectionPoolResponse": {
            "type": "object",
            "properties": {
                "connections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/connection.ConnectionInfoResponse"
                    }
                },
                "poolSize": {
                    "type": "integer"
                }
            }
        },
        "connection.ConnectionRequest": {
            "type": "object",
            "required": [
                "connectionType",
                "manufacturer",
                "model"
            ],
            "properties": {
                "certificate": {
                    "description": "для certificate",
                    "type": "string",
                    "example": "cert-abc-123"
                },
                "connectionType": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ConnectionTypeEnum"
                        }
                    ],
                    "example": "password"
                },
                "endpointURL": {
                    "type": "string",
                    "example": "opc.tcp://KHRLLW_-340595:4840/HEIDENHAIN/NC"
                },
                "key": {
                    "type": "string",
                    "example": "secret"
                },
                "manufacturer": {
                    "type": "string",
                    "example": "Heidenhain"
                },
                "mode": {
                    "description": "OPC UA MessageSecurityMode",
                    "allOf": [
                        {
                            "$ref": "#/definitions/connection.MessageSecurityModeEnum"
                        }
                    ],
                    "example": "SignAndEncrypt"
                },
                "model": {
                    "type": "string",
                    "example": "TNC640"
                },
                "password": {
                    "description": "для password",
                    "type": "string",
                    "example": "secret"
                },
                "policy": {
                    "description": "OPC UA SecurityPolicy",
                    "allOf": [
                        {
                            "$ref": "#/definitions/connection.SecurityPolicyEnum"
                        }
                    ],
                    "example": "Basic256Sha256"
                },
                "username": {
                    "description": "для password",
                    "type": "string",
                    "example": "client1"
                }
            }
        },
        "connection.ConnectionStatusEnum": {
            "type": "string",
            "enum": [
                "OK",
                "FAIL",
                "NOT FOUND",
                "HEALTHY",
                "UNHEALTHY",
                "CONNECTED",
                "DISCONNECTED",
                "ERROR",
                "TIMEOUT",
                "AUTH_FAILED"
            ],
            "x-enum-comments": {
                "StatusAuthFailed": "Ошибка аутентификации",
                "StatusConnected": "Соединение установлено",
                "StatusDisconnected": "Соединение разорвано",
                "StatusError": "Ошибка соединения",
                "StatusHealthy": "Соединение здорово и работает",
                "StatusTimeout": "Таймаут соединения",
                "StatusUnhealthy": "Соединение есть, но есть проблемы"
            },
            "x-enum-descriptions": [
                "",
                "",
                "",
                "Соединение здорово и работает",
                "Соединение есть, но есть проблемы",
                "Соединение установлено",
                "Соединение разорвано",
                "Ошибка соединения",
                "Таймаут соединения",
                "Ошибка аутентификации"
            ],
            "x-enum-varnames": [
                "StatusOK",
                "StatusFail",
                "StatusNotFound",
                "StatusHealthy",
                "StatusUnhealthy",
                "StatusConnected",
                "StatusDisconnected",
                "StatusError",
                "StatusTimeout",
                "StatusAuthFailed"
            ]
        },
        "connection.DisconnectResponse": {
            "type": "object",
            "required": [
                "disconnected"
            ],
            "properties": {
                "disconnected": {
                    "type": "boolean"
                }
            }
        },
        "connection.IDRequest": {
            "type": "object",
            "required": [
                "ID"
            ],
            "properties": {
                "ID": {
                    "type": "integer"
                }
            }
        },
        "connection.IDResponse": {
            "type": "object",
            "required": [
                "ID"
            ],
            "properties": {
                "ID": {
                    "type": "integer"
                }
            }
        },
        "connection.MessageSecurityModeEnum": {
            "type": "string",
            "enum": [
                "None",
                "Sign",
                "SignAndEncrypt"
            ],
            "x-enum-varnames": [
                "ModeNone",
                "ModeSign",
                "ModeSignAndEncrypt"
            ]
        },
        "connection.PollingResponse": {
            "type": "object",
            "required": [
                "polled"
            ],
            "properties": {
                "polled": {
                    "type": "boolean"
                }
            }
        },
        "connection.SecurityPolicyEnum": {
            "type": "string",
            "enum": [
                "None",
                "Basic128Rsa15",
                "Basic256",
                "Basic256Sha256"
            ],
            "x-enum-varnames": [
                "PolicyNone",
                "PolicyBasic128Rsa15",
                "PolicyBasic256",
                "PolicyBasic256Sha256"
            ]
        },
        "connection.StartPollingRequest": {
            "type": "object",
            "required": [
                "ID",
                "timeout"
            ],
            "properties": {
                "ID": {
                    "type": "integer"
                },
                "timeout": {
                    "type": "integer"
                }
            }
        },
        "models.ConnectionConfig": {
            "type": "object",
            "properties": {
                "config": {}
            }
        },
        "models.ConnectionTypeEnum": {
            "type": "string",
            "enum": [
                "anonymous",
                "password",
                "certificate"
            ],
            "x-enum-varnames": [
                "ConnectionAnonymous",
                "ConnectionPassword",
                "ConnectionCertificate"
            ]
        },
        "swagger.CheckConnectionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/connection.ConnectionInfoResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Successfully get connection info"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "type": {
                    "type": "string",
                    "example": "object"
                }
            }
        },
        "swagger.DisconnectResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/connection.DisconnectResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Successfully disconnected"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "type": {
                    "type": "string",
                    "example": "object"
                }
            }
        },
        "swagger.GetConnectionPoolResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/connection.ConnectionPoolResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Successfully get connection pool"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "type": {
                    "type": "string",
                    "example": "object"
                }
            }
        },
        "swagger.IDResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/connection.IDResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Successfully connected"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "type": {
                    "type": "string",
                    "example": "object"
                }
            }
        },
        "swagger.IncorrectDataError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 400
                        },
                        "message": {
                            "type": "string",
                            "example": "Некорректные данные"
                        }
                    }
                },
                "status": {
                    "type": "string",
                    "example": "IncorrectDataError"
                }
            }
        },
        "swagger.IncorrectFormatError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 400
                        },
                        "message": {
                            "type": "string",
                            "example": "Неверный формат запроса"
                        }
                    }
                },
                "status": {
                    "type": "string",
                    "example": "IncorrectFormatError"
                }
            }
        },
        "swagger.InternalServerError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 500
                        },
                        "message": {
                            "type": "string",
                            "example": "Внутренняя ошибка сервера"
                        }
                    }
                },
                "status": {
                    "type": "string",
                    "example": "InternalServerError"
                }
            }
        },
        "swagger.NotFoundError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 404
                        },
                        "message": {
                            "type": "string",
                            "example": "Данные не найдены"
                        }
                    }
                },
                "status": {
                    "type": "string",
                    "example": "NotFoundError"
                }
            }
        },
        "swagger.PollingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/connection.PollingResponse"
                },
                "message": {
                    "type": "string",
                    "example": "Polling started/stopped for machine"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "type": {
                    "type": "string",
                    "example": "object"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "OpcUaService API",
	Description:      "API для работы с протоколом OPC UA",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
